In [30]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display
import os
base = os.path.dirname('/u/weim/lob/notebooks/performance_benchmark_strategies_damping_factors.ipynb')
parent_dir = os.path.dirname(base)

In [31]:

damping_factor = 1.0

noise=pd.read_csv(f'{parent_dir}/results/performance_benchmarks_noise_environment_damping_factor_{damping_factor}.csv', index_col=0)
flow=pd.read_csv(f'{parent_dir}/results/performance_benchmarks_flow_environment_damping_factor_{damping_factor}.csv', index_col=0)
# strat=pd.read_csv(f'{parent_dir}/results/performance_benchmarks_strategic_environment_damping_factor_{damping_factor}.csv', index_col=0)

print('#######')
print('base case')
print('#######')
print()
print('noise environment:')
display(noise) 

print('flow environment:')
display(flow)

# print('strategic environment:')
# display(strat)



noise=pd.read_csv(f'{parent_dir}/results/performance_benchmarks_noise_environment_damping_factor_{damping_factor}_market_scale2.csv', index_col=0)
flow=pd.read_csv(f'{parent_dir}/results/performance_benchmarks_flow_environment_damping_factor_{damping_factor}_market_scale2.csv', index_col=0)
# strat=pd.read_csv(f'{parent_dir}/results/performance_benchmarks_strategic_environment_damping_factor_{damping_factor}_market_scale2.csv', index_col=0)

print('#######')
print('bases market intensity scales by a factor of 2')
print('#######')
print()
print('noise environment:')
display(noise) 

print('flow environment:')
display(flow)

# print('strategic environment:')
# display(strat)

noise=pd.read_csv(f'{parent_dir}/results/performance_benchmarks_noise_environment_damping_factor_{damping_factor}_sgn_imb.csv', index_col=0)
flow=pd.read_csv(f'{parent_dir}/results/performance_benchmarks_flow_environment_damping_factor_{damping_factor}_sgn_imb.csv', index_col=0)
# strat=pd.read_csv(f'{parent_dir}/results/performance_benchmarks_strategic_environment_damping_factor_{damping_factor}_market_scale2.csv', index_col=0)

print('#######')
print('I = sign(I)')
print('#######')
print()
print('noise environment:')
display(noise) 

print('flow environment:')
display(flow)

#######
base case
#######

noise environment:

      market_m  market_std  sl_m  sl_std  linear_sl_m  linear_sl_std
lots
10       -0.51        0.43  0.52    2.00        -0.34           2.25
20       -0.93        0.51 -0.07    2.27        -0.70           2.39
30       -1.28        0.55 -0.59    2.41        -1.22           2.34
40       -1.59        0.58 -1.18    2.49        -1.71           2.41
100      -3.22        0.67 -3.53    2.18        -4.49           2.30

flow environment:

      market_m  market_std  sl_m  sl_std  linear_sl_m  linear_sl_std
lots
10       -0.50        0.42  0.39    2.03        -0.10           2.13
20       -0.92        0.50 -0.53    2.35        -0.47           2.18
30       -1.26        0.54 -1.75    2.51        -1.12           2.26
40       -1.57        0.57 -2.60    2.44        -1.75           2.28
100      -3.20        0.67 -5.15    2.15        -5.63           2.23

#######
bases market intensity scales by a factor of 2
#######

noise environment:

      market_m  market_std  sl_m  sl_std  linear_sl_m  linear_sl_std
lots
10       -0.51        0.45  1.02    1.47         0.59           2.44
20       -0.95        0.54  0.63    1.97         0.21           2.45
30       -1.29        0.58  0.20    2.36        -0.07           2.40
40       -1.61        0.61 -0.10    2.52        -0.46           2.49
100      -3.24        0.71 -2.75    2.97        -2.82           2.67

flow environment:

      market_m  market_std  sl_m  sl_std  linear_sl_m  linear_sl_std
lots
10       -0.51        0.46  0.94    1.67         0.68           2.24
20       -0.94        0.54  0.22    2.33         0.44           2.19
30       -1.29        0.58 -0.69    2.64         0.04           2.21
40       -1.60        0.61 -1.83    2.86        -0.42           2.33
100      -3.23        0.70 -5.70    2.32        -3.78           2.58

#######
I = sign(I)
#######

noise environment:

      market_m  market_std  sl_m  sl_std  linear_sl_m  linear_sl_std
lots
10       -0.51        0.43  0.52    2.00        -0.34           2.25
20       -0.93        0.51 -0.07    2.27        -0.70           2.39
30       -1.28        0.55 -0.59    2.41        -1.22           2.34
40       -1.59        0.58 -1.18    2.49        -1.71           2.41
100      -3.22        0.67 -3.53    2.18        -4.49           2.30

flow environment:

      market_m  market_std  sl_m  sl_std  linear_sl_m  linear_sl_std
lots
10       -0.50        0.43  0.06    2.21         0.14           2.00
20       -0.92        0.51 -2.10    2.37        -0.39           2.11
30       -1.26        0.56 -3.25    2.15        -1.20           2.23
40       -1.57        0.59 -3.87    1.99        -2.11           2.26
100      -3.20        0.68 -5.96    2.07        -7.11           2.15